# Site Details
site_name: Ombi Docs
site_description: The official guide for Ombi 
site_author: Ombi-App
site_url: https://docs.ombi.app
edit_uri: https://github.com/Ombi-App/Ombi.Docs/edit/development/docs/
repo_url: https://github.com/Ombi-App/Ombi.Docs
repo_name: Ombi-App/Ombi.Docs


# Site appearance (logos, colours, icons)
# Ombi orange is hex #e37200
theme:
  name: material
  language: en
  code_wrap: true
  features:
    - navigation.tabs
    #- navigation.tabs.sticky #(insiders only, reaching out RE open-source access possibility)
    - navigation.instant
  favicon: assets/images/ombi/favicon.ico
#  logo: assets/images/apple-touch-icon.png
#  palette:
#    primary: tbd
#    accent: e37200 #Ombi

# Additional links
extra:
  social:
    - icon: "fontawesome/brands/discord"
      link: "https://discord.gg/Sa7wNWb"
    - icon: "fontawesome/brands/twitch"
      link: "https://www.twitch.tv/tidusjar"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/intent/follow?screen_name=tidusjar"
    - icon: "fontawesome/brands/patreon"
      link: "https://patreon.com/tidusjar/Ombi"
    - icon: "fontawesome/brands/paypal"
      link: "https://paypal.me/PlexRequestsNet"

# Function extensions
plugins:
  - search
  - git-revision-date-localized

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.inlinehilite

# Navigation Layout
nav:
  - Home: index.md
  - Installation: installation.md
  - Updating: updating.md
  - FAQ: faq.md
  - Common Errors: common-errors.md
  - Settings: 
    - Generic Settings: settings/ombi-settings.md
    - All the Arrs: settings/arr-settings.md
    - Authentication: settings/authentication.md
    - Customization: settings/customization.md
    - DogNzb: settings/dognzb.md
    - Issues: settings/issues.md
    - Landing Page: settings/landing-page.md
    - Mobile App: settings/mobile-app.md
    - Scheduled Tasks: settings/scheduled-tasks.md
    - User Importer: settings/import-users.md
    - Vote: settings/voting.md
    - Notifications:
      - Template Variables: settings/notifications/template-variables.md
      - Discord: settings/notifications/discord.md
      - Email: settings/notifications/email.md
      - Mass Email: settings/notifications/mass-email.md
      - Newsletter: settings/notifications/newsletter.md
      - Pushbullet: settings/notifications/pushbullet.md
      - Pushover: settings/notifications/pushover.md
      - Slack: settings/notifications/slack.md
      - Telegram: settings/notifications/telegram.md
      - Twilio: settings/notifications/twilio.md
  - Info:
    - Alternate Databases: info/alternate-databases.md
    - Migrating Databases: info/migrating-databases.md
    - API Information: info/api-information.md
    - Backing Up: info/backing-up.md
    - Common Themes: info/common-themes.md
    - Docker Containers: info/docker-containers.md
    - Ombi & Tautulli: info/ombi-tautulli.md
    - Request Flow: info/request-workflow.md
    - Reverse Proxying: info/reverse-proxy.md
    - Roles and Notifications: info/roles-and-notifications.md
    - Startup Parameters: info/startup-parameters.md
    - Suggesting Features: info/feature-suggestions.md
    - User Roles: info/user-roles.md
  - Development:
    - Building Ombi: development/building-ombi.md
    - Translating Ombi: development/translations.md
  - Archive:
    - Prerequisites: archive/prerequisites.md
    - V4 Specific Proxying: archive/v4-specific-proxy.md
