site_name: Ombi Docs
site_description: The official guide for Ombi 
site_author: Ombi-App
site_url: https://docs.ombi.app

repo_url: https://github.com/Ombi-App/Ombi.Docs
repo_name: Ombi-App/Ombi.Docs
edit_uri: https://github.com/Ombi-App/Ombi.Docs/edit/development/docs/"

# Site theming (logos, colours, icons)
# Ombi orange is hex #e37200
theme:
  name: material
  language: en
  features:
    - navigation.instant
  favicon: assets/images/ombi/favicon.ico
#  logo: assets/images/apple-touch-icon.png
#  palette:
#    primary: tbd
#    accent: e37200 #Ombi

extra:
  social:
    - icon: "fontawesome/brands/discord"
      link: "https://discord.gg/Sa7wNWb"
    - icon: "fontawesome/brands/twitch"
      link: "https://www.twitch.tv/tidusjar"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/intent/follow?screen_name=tidusjar"
    - icon: "fontawesome/brands/patreon"
      link: "https://patreon.com/tidusjar/Ombi"
    - icon: "fontawesome/brands/paypal"
      link: "https://paypal.me/PlexRequestsNet"
    
# Navigation Layout
nav:
  - Home: index.md
  - Installation: installation.md
  - Updating: updating.md
  - FAQ: faq.md
  - Common Errors: common-errors.md
  - Settings: 
    - Generic Settings: settings/ombi-settings.md
    - All the Arrs: settings/arr-settings.md
    - Customization: settings/customization.md
    - Reverse Proxying: settings/reverse-proxy.md
    - Notifications:
        Template Variables: settings/notifications/template-variables.md
        Discord: settings/notifications/discord.md
  - Info:
      Docker Containers: info/docker-containers.md
      Request Flow: info/request-workflow.md
      Suggesting Features: info/feature-suggestions.md
  - Scripting:
      Ombi & Tautulli: scripting/ombi-tautulli.md
  - Archive:
      Prerequisites: archived/prerequisites.md
      V4 Specific Proxying: archived/v4-specific-proxy.md
