site_name: Ombi Docs
theme:
  name: material
nav:
  - Home: index.md
  - Installation: installation.md
  - Settings: 
    - Reverse Proxying: settings\reverse-proxy-v4.md
    - Reverse Proxy Examples: settings\reverse-proxy-examples.md
