blank_issues_enabled: false
contact_links:
  - name: Docs
    url: https://docs.ombi.app/
    about: The Ombi documentation should help guide you through installation and setup as well as help resolve common problems and answer frequently asked questions
  - name: Ombi Repo
    url: https://github.com/Ombi-App/Ombi
    about: If this bug is to do with a bug in the Ombi application itself, submit the bug over on this repo instead.
  - name: Reddit support
    url: https://www.reddit.com/r/Ombi
    about: Ask questions about Ombi
  - name: Feature suggestions
    url: https://ombifeatures.featureupvote.com
    about: Share your suggestions or ideas to make Ombi better!