blank_issues_enabled: false
contact_links:
  - name: Ombi Repo
    url: https://github.com/Ombi-App/Ombi/issues
    about: If this bug is to do with a bug in the Ombi application itself, submit the bug over on this repo instead.
  - name: Reddit support
    url: https://www.reddit.com/r/Ombi
    about: Ask questions about Ombi
  - name: Feature suggestions
    url: https://ombifeatures.featureupvote.com
    about: Share your suggestions or ideas to make Ombi better!